import = ["/home/hiraeth/.config/alacritty/themes/themes/nord.toml"]

[cursor.style]
blinking = "On"
shape = "Block"

[font]
size = 8.0

[font.bold]
family = "Maple Mono NF"

[font.bold_italic]
family = "Maple Mono NF"

[font.italic]
family = "Maple Mono NF"

[font.normal]
family = "Maple Mono NF"

[mouse]
hide_when_typing = true
